spring.config.import=optional:configserver:http://localhost:1212
server.port=8081

spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.config.import=optional:configserver:http://localhost:1578
